title: Muhammad Ali # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have been working as a contracted Software Engineer for Salesforce focusing on developing features
  for B2B and B2C Commerce Clouds. The technologies i'm using day to day in my current role are Typescript, LWC, Jest and some Java. 
  I love problem solving and learning new technologies as well as knowledge sharing. 
   <br><br>
   When I'm not at my desk working, you'll find me on walks with family or on a road trips to the mountains. 
  <br><br>
  <a href="https://www.linkedin.com/in/muhammad-ali-b4b13b17a/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
