title: Muhammad Ali # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm currently working as a C#.NET Web Application Developer Intern at UVic. 
  I'm excited to be expecting to graduate in December and I'm currently looking for full time opportunities!  
   <br><br>
   When I'm not at my desk working, you'll find me on walks with family or on a road trips to the mountains. 
  <br><br>
  <a href="https://www.linkedin.com/in/muhammad-ali-b4b13b17a/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
